### ISSUE TITLE
Support for SSH public keys

### ISSUE THREAD

**Issue by nhlfr** [giantswarm/k8scloudconfig#10]
We need to inject SSH keys into cloudconfig.

Most probably, we will do it by providing ssh keys via extension, so the external operators can fill it with data received from cert-operator. Since cert-operator is not implemented yet, the aws- and kvm-operator can temporarily provide the keys by themselves.

**Comment by teemow** [comment]
Even more: There should be distinct users. Nobody should connect with the core user. Everybody should have it's own user.

It would be awesome if we could hook this up to dex and read users and keys from there. 

ping @puja108

**Comment by puja108** [comment]
+1 we need distinct users, on the one side it's about managing access, on the other side it's about being able to identify who did what (i.e. for audits)

I don't think Dex has that kind of functionality, it's pretty dumb from what I've seen, we would need a real IdM solution for that kind of foo. Or sth interfacing with Vault or so that gives us revokability of keys maybe?

**Comment by asymmetric** [comment]
Does this issue need to be specced more? It's not clear to me if it's actionable at this point, i.e. should we expand the issue to using multiple users?

**Comment by puja108** [comment]
Yes, might need some minor speccing at least as @teemow was also mentioning maybe using the ssh backend of Vault for this.

**Comment by puja108** [comment]
The comment I meant from Timo:
> just stumbled upon the ssh backend in vault. let's keep this in mind. would be totally awesome to have this in vault too. so once you are in the github group you can connect to the vaults and issue yourself certificates and ssh keys

**Comment by webwurst** [comment]
We could use GitHub to read users and keys like https://github.com/webwurst.keys.

**Comment by puja108** [comment]
Keybase might also be an option?

**Comment by calvix** [comment]
@puja108 @teemow @xh3b4sd 

We need to continue on this.
Separate OS account for each person is requested by security (because of audit reasons).
So we need to have a way how to provide list of users and their ssh to the k8scloudconfig.

**Comment by xh3b4sd** [comment]
This should be quite easy. See https://github.com/giantswarm/kubernetesd/blob/bea1a75406b6442b59ff04de51009b57462462d2/helm/kubernetesd-chart/templates/configmap.yaml#L65. We can just add the puclic keys as we need them to the installations repo and wire them through the kubernetesd configmap. The guest cluster gets the list injected here: https://github.com/giantswarm/kubernetesd/blob/13730c8d47da239f5aecf8712f7f4123196cf3f4/service/creator/cluster.go#L227. The keys are already handled in the actual CC templates. See https://github.com/giantswarm/k8scloudconfig/blob/a33a8562386695466bd8c76e1e4e9727d6dc7e7a/templates.go#L6 and https://github.com/giantswarm/k8scloudconfig/blob/a33a8562386695466bd8c76e1e4e9727d6dc7e7a/templates.go#L1315.

**Comment by calvix** [comment]
ok so we need to add support for multiple user

**Comment by xh3b4sd** [comment]
@calvix AFAIK you wanted to work on this these days. Please assign yourself and move the issue to the WIP column when you work on it. <3

**Comment by calvix** [comment]
So I made first stuff, I am not completely sure if this is right and I  got all the things I need to change, so please revise @xh3b4sd @kopiczko @rossf7 

PRs:

installations - https://github.com/giantswarm/installations/pull/97
cluster tpr - https://github.com/giantswarm/clustertpr/pull/35
kubernetesd - https://github.com/giantswarm/kubernetesd/pull/266
k8scloudconfig - https://github.com/giantswarm/k8scloudconfig/pull/188


tested on gauss and seems to be working as expected
```
calvix@ip-10-1-1-248 ~ $ ls /home/
calvix  fgimenez  joe       marcelmue  oponder  r7vme   teemow  vol
core    jgsqware  kopiczko  marian     puja     rossf7  tobias  xh3b4sd
calvix@ip-10-1-1-248 ~ $ vim /^C
calvix@ip-10-1-1-248 ~ $ sudo su
```

**Comment by kopiczko** [comment]
Do we need that in kvm-operator?

**Comment by calvix** [comment]
@kopiczko yes, after I got all stuff on AWS I will also update kvm-operator

**Comment by calvix** [comment]
merged
