### ISSUE TITLE
Always use HTTPS to talk to API server

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/k8scloudconfig#103]
The `k8s-policy-controller` talks to the api server [over HTTP on the insecure port](https://github.com/giantswarm/k8scloudconfig/blob/86f54470ac49b178940aabc0574c2e753c1c52a5/templates.go#L883).

We should use the certs and HTTPS.

**Comment by xh3b4sd** [comment]
AFAIK this is done. Closing.
