### ISSUE TITLE
policy-controller and leader-elector still use .Cluster.Docker.ImageNamespace

### ISSUE THREAD

**Issue by rossf7** [giantswarm/k8scloudconfig#107]
For all other docker images we have the fully qualified image in `clustertpr`. Currently .Cluster.Docker.ImageNamespace is `giantswarm` so we use Docker Hub and not Quay.io.

See https://github.com/giantswarm/k8scloudconfig/blob/master/templates.go#L871
https://github.com/giantswarm/k8scloudconfig/blob/master/templates.go#L901

Ping @JosephSalisbury in case this affects the re-tagger.

**Comment by JosephSalisbury** [comment]
We'll need to use quay for these

**Comment by puja108** [comment]
we removed leader elector and moved policy controller to quay
