### ISSUE TITLE
Make calico-node unit wait for domains

### ISSUE THREAD

**Issue by rossf7** [giantswarm/k8scloudconfig#109]
Towards giantswarm/giantswarm#1381

Tracking for yesterday's debugging with @calvix and @asymmetric. This cluster startup problem was found. The calico-node unit should wait for the domains and not etcd.

Change has been made in k8scloudconfig and needs to be tested on AWS.

**Comment by rossf7** [comment]
For a successful test the ingress controller pods should start and ELB should be healthy.

**Comment by asymmetric** [comment]
Works.
