### ISSUE TITLE
Conflicting usecases for etcd

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/k8scloudconfig#12]
We have the following situation:

* The KVM setup has an outer and an inner etcd
* The AWS operator currently only handles one "layer"

This means that the etcd2 unit file has directives that don't work on AWS, e.g. 

* [this one](https://github.com/giantswarm/k8scloudconfig/blob/2afcdc25c44ca95fa8fc0ac8568edf08bc7d12ab/templates/master.yaml#L527), which expects the outer etcd to be there
* [this one](https://github.com/giantswarm/k8scloudconfig/blob/2afcdc25c44ca95fa8fc0ac8568edf08bc7d12ab/templates/master.yaml#L533), that configures etcd to listen on the same port as the k8s API. We run etcd on the one master so this doesn't work.

How should we approach this?

Should we move the etcd configuration out of this repo, and into the specific ones?

**Comment by xh3b4sd** [comment]
AFAIK the idea was to separate etcd from the master at some point. Etcd is then running in a clustered mode with three nodes managed by the etcd-operator. The first step for AWS could be to simulate the outer etcd. I thought this is already done. So running etcd within the AWS installation and pointing the guest cluster instances to it should do the trick. On AWS we can then simply start etcd clusters per guest cluster and nothing changes in the k8scloudconfig. So running the outer etcd on AWS should solve the problem. Right? I never saw the AWS setup but I reckon we are running some CoreOS instances for the host Kubernetes and our Giantswarm internal microservices anyway. There should be already an etcd. We can simply reuse this one then and point the guest clusters to it. This sucks but would let us move with the MVP. Later we roll with the separated etcd clusters per guest cluster in an automated fashion.

**Comment by asymmetric** [comment]
The consensus is that on AWS we should stick as much as possible to the KVM setup, that means:

* having an outer etcd instance (or a cluster)
* not changing the unit file
