### ISSUE TITLE
Make Calico MTU optional (only needed in KVM setup)

### ISSUE THREAD

**Issue by puja108** [giantswarm/k8scloudconfig#126]
AFAIK we are setting lower MTU because if the flannel setup we have with KVM. On AWS and other providers we might not need this so we should have this optional.

**Comment by calvix** [comment]
i would say this is not a big priority,  because the default MTU is like 50 or so bigger so the  difference is marginal and unless you are transferring a tons of really big files you wont notice any degraded performance

**Comment by rossf7** [comment]
Closing ping @puja108 @calvix
