### ISSUE TITLE
Check if change of cgroup driver is ok

### ISSUE THREAD

**Issue by puja108** [giantswarm/k8scloudconfig#133]
Because of https://github.com/kubernetes/kubernetes/issues/43805 there's some incompatibility in cgroup drivers moving kubelet to k8s 1.6+

We had
`native.cgroupdriver=systemd`
and I tried starting kubelet with `--cgroup-driver=systemd` but that didn't work.

I now changed our docker config to `native.cgroupdriver=cgroupfs`. CoreOS themselves are now also going with the Docker default of cgroupfs (https://github.com/coreos/bugs/issues/1435) so I think this is secure.

Still we want to re-check if this is actually the right decision as most of us don't really understand the implications of it.

@teemow WDYT?

**Comment by teemow** [comment]
@puja108 within the old platform we ran into some issues with systemd units and docker and the systemd cgroup driver fixed that for us. but if now docker is the way to go i am fine. upgrade to cgroup v2 will be fun :D

**Comment by teemow** [comment]
oh. can this be closed since we are already on 1.6?

**Comment by puja108** [comment]
yes, this issue was mainly to get your input on the issue, so lets close and keep an eye on it if we run into any issues
