### ISSUE TITLE
fetch kubectl URL from configmap

### ISSUE THREAD

**Issue by calvix** [giantswarm/k8scloudconfig#136]
this has to be dynamic not hardcoded
https://github.com/giantswarm/k8scloudconfig/pull/135/files#diff-44e6c54f43ac9be31121348d531e697fR662

message from Tim: 
This should actually be configured via the clustertpr. See https://github.com/giantswarm/kubernetesd/blob/a8528d72f2a2ff7b37c5d6674684a03c543830c1/kubernetes/configmap.yaml#L90. I realize now that this is not specific to KVM so the config should be moved in kubernetesd. Anyway, at the moment here the URL should be replaced by something like this.
``
curl -o /opt/bin/kubectl {{ .Cluster.KVM.Kubectl.GoogleAPI.URL }}
``
Lets please create an issue for this and address it in the next steps.

**Comment by JosephSalisbury** [comment]
I feel like we should be using our kubectl docker image, as opposed to downloading it

**Comment by asymmetric** [comment]
@JosephSalisbury I agree, since that's what we do for other binaries (Hyperkube). What do the others think? @giantswarm/team-positive

**Comment by xh3b4sd** [comment]
My two cents. 

- We should configure the URL as described in my PR comment.
- We should use whatever kubectl is appropriate. In case we have another one than the official one, fine. Just do the do.

**Comment by asymmetric** [comment]
Does it make sense to allow different `kubectl` versions for KVM and AWS? i.e. having two separate flags?

**Comment by xh3b4sd** [comment]
I do not think so because the guest clusters should be the same. Is there a special reason why you think this should be different?

**Comment by asymmetric** [comment]
Nope, just checking as I haven't had much to do with kubernetesd or KVM much. All good.
