### ISSUE TITLE
Use DNS autoscaler

### ISSUE THREAD

**Issue by puja108** [giantswarm/k8scloudconfig#146]
More recent installations of k8s use an autoscaler (based on #nodes and #cores in the cluster) to ensure an appropriate number of DNS pods:
https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns-horizontal-autoscaler

This is currently not urgent as I think we're ok with spawning 3 replicas (we're just overprovisioning DNS a bit, but that's not so bad).

**Comment by kopiczko** [comment]
It's in later. Closing. @puja108 feel free to reopen and put in SIG Operator inbox.
