### ISSUE TITLE
Use addon-manager

### ISSUE THREAD

**Issue by puja108** [giantswarm/k8scloudconfig#147]
The K8s addon-manager (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager) can ensure that certain manifests (by default in '/etc/kubernetes/addons') are ensured to be running (created when not there) or even reconciled (changed back to defaults if changed).

The current version can be run like following: https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/resources/manifests/kube-addon-manager.yaml

It runs in hostnetwork so it can be there before Calico and can actually even schedule calico and other things, not sure how it handles priorities so we still might want to have calico outside. I saw some things that EnsureExists has a higher prio than Reconcile. Otherwise it can just handle all the addons that we need running, incl. DNS, IC, StorageClasses, RBAC roles and bindings.

Things need to be in `kube-system` namespace and have a label `addonmanager.kubernetes.io/mode: EnsureExists` or `addonmanager.kubernetes.io/mode: Reconcile` in their yamls. The yamls should live in `/etc/kubernetes/addons` and don't need to be applied manually anymore AFAIK.

Not sure if it also handles updates, but that could be interesting to update things running in clusters without needing to roll anything.

WDYT @rossf7 @calvix but maybe not so urgent.

**Comment by calvix** [comment]
That would be awesome, we still have to figure out how to do this with calico but anyway good direction.

**Comment by rossf7** [comment]
Yes I think we should close. This is covered by giantswarm/giantswarm#1902 and we'll be using `chart-operator` to deploy addons.

**Comment by calvix** [comment]
Yep we can close.
