### ISSUE TITLE
mount /var/log/pods in kubelets

### ISSUE THREAD

**Issue by puja108** [giantswarm/k8scloudconfig#160]
The kubelet creates symlinks in `/var/log/pods/` for the logs pertaining to a pod. As that folder is ephemeral, these symlinks disappear when we restart kubelets. This results in errors like the following:

```
kubectl -n kube-system logs nginx-ingress-controller-1251340348-40hxd
failed to open log file "/var/log/pods/43c6cec7-5bfa-11e7-b419-02a1a99a34d5/nginx-ingress-controller_0.log": open /var/log/pods/43c6cec7-5bfa-11e7-b419-02a1a99a34d5/nginx-ingress-controller_0.log: no such file or directory%```

To solve this we need to mount the `/var/log/pods` rw when we start the kubelet hyperkube container

**Comment by puja108** [comment]
We should also make similar changes on the host cluster in hive/terraform ping @r7vme @calvix @teemow

**Comment by kopiczko** [comment]
@puja108 it looks more like SIG host cluster than operator.

**Comment by puja108** [comment]
@kopiczko this is both, we need it in `k8scloudconfig` for guest clusters and also in the host cluster setups (hive/terraform/...)

**Comment by calvix** [comment]
fix for aws-terraform and hive are done

**Comment by puja108** [comment]
Alright, I guess we can close this
