### ISSUE TITLE
For fluentd we need to have whole /var/log/ mounted into kubelet container

### ISSUE THREAD

**Issue by r7vme** [giantswarm/k8scloudconfig#164]
See: https://github.com/coreos/bugs/issues/1614

Currently we have only `/var/log/pods` mounted https://github.com/giantswarm/k8scloudconfig/blob/master/templates.go#L33

**Comment by r7vme** [comment]
cc: @xh3b4sd @calvix this affects probably all customers

**Comment by webwurst** [comment]
Customer issue for cargarantie: https://github.com/giantswarm/cargarantie/issues/43
