### ISSUE TITLE
kubelet uses autogenerated self-signed certificates

### ISSUE THREAD

**Issue by r7vme** [giantswarm/k8scloudconfig#167]
There two options in kubelet that we are leaving with default value

>>> --tls-cert-file string                                    File containing x509 Certificate used for serving HTTPS (with intermediate certs, if any, concatenated after server cert). If --tls-cert-file and --tls-private-key-file are not provided, a self-signed certificate and key are generated for the public address and saved to the directory passed to --cert-dir.
     --tls-private-key-file string                             File containing x509 private key matching --tls-cert-file.

Kubelet ends up with self-signed autogenerated certificate on port 10250. 

This affects at least Prometheus which forced to ignore tls checks.

**Comment by calvix** [comment]
@puja108 should be added to security issues i thnik

**Comment by puja108** [comment]
Yes, we need to set those certs, this is also part of https://github.com/giantswarm/giantswarm/issues/1720

cc @jgsqware

**Comment by calvix** [comment]
should be fixed for `k8scloudconfig`,  `hive` and `aws-terraform` (classic trio)

**Comment by puja108** [comment]
let's check if we fixed it

**Comment by puja108** [comment]
seems it's not done so we should do it

**Comment by calvix** [comment]
yep still not there :)

**Comment by Lennie** [comment]
Is there a plan what the solution should look like ? Because it looks like it hasn't been fixed ?

**Comment by puja108** [comment]
@jgsqware this is part of CIS work, can you check if this is still open and otherwise see when we want to do this, shouldn't be hard as AFAIK we already have the certs on the machine, just need to wire them up.

**Comment by jgsqware** [comment]
Related to this: https://github.com/giantswarm/giantswarm/pull/2223
