### ISSUE TITLE
Choose sane setting for log-rotation

### ISSUE THREAD

**Issue by webwurst** [giantswarm/k8scloudconfig#172]
See discussion in [#ops](https://gigantic.slack.com/archives/C02MS174K/p1502191201478981).

Currently we use: `--log-opt max-size=50m --log-opt max-file=1`

This might lead to lost log-lines when forwarding logs to Elasticsearch:
- Log shippers like `fluentd`, `filebeat` etc. watch for changes on the conainers log files provided by Docker.
- The log shipper might hang for some seconds because of cpu or network or something.
- During that period some logs might be written to disk.
- If the `max-size` is reached, the current log file gets deleted and a new file is created.
- The log shipper is fine again and reads from the new file, 
  - but it missed the last logs from the file before **(!)**

Possible solution:
- Increase `--log-opt max-file`

**Comment by JosephSalisbury** [comment]
Is this an actual problem? Wouldn't increasing `max-file` have the same issue as well?

**Comment by webwurst** [comment]
If you have `max-file=2` and log shipper hangs temporarily on the end of the second file while this reaches `max-size`, then the first file would be deleted. But that one was already processed by the log-shipper, so all fine with that. A new file is created and the log shipper still has time to finish reading its current file before moving on the new one.

**Comment by webwurst** [comment]
And this is an actual problem if a customer has set up alerts for special log lines showing up in his central log database. Some might just be missed.

**Comment by JosephSalisbury** [comment]
Ah, `max-file`, not `max-size`. I see now. Thanks!

**Comment by teemow** [comment]
@webwurst feel free to create a PR.

**Comment by calvix** [comment]
done
