### ISSUE TITLE
try to use go-bindata

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/k8scloudconfig#174]
We could use gobindata and push the output of the yaml files to the repository.

We can ensure gobindata output is in sync with yaml files by adding a test.

**Comment by teemow** [comment]
Please see https://github.com/giantswarm/k8scloudconfig/issues/22

:joy:

**Comment by calvix** [comment]
I felt the go-bindata hate wave too :)

**Comment by kopiczko** [comment]
I have an idea how to work with that. I'll try to timebox that. Let's see.

**Comment by xh3b4sd** [comment]
I would like to close this. Either invest an hour now or never do it. I want to remove such issues from the board.
