### ISSUE TITLE
set-ownership-etcd-data-dir.service fails on kvm

### ISSUE THREAD

**Issue by calvix** [giantswarm/k8scloudconfig#228]
service `set-ownership-etcd-data-dir.service` on guest cluster fails on kvm

there is a problem that in aws the directory is on ebs but on kvm its mounted disk from underlying fs.
This means that there has to be an event for mount and that means delay.
```
Nov 01 11:16:12 master-g4pnu-1893516417-g634g systemd[1]: Starting Set ownership to etcd3 data dir...
Nov 01 11:16:12 master-g4pnu-1893516417-g634g chmod[1097]: /usr/bin/chmod: /etc/kubernetes/data/etcd: No such file or directory
Nov 01 11:16:12 master-g4pnu-1893516417-g634g systemd[1]: set-ownership-etcd-data-dir.service: Main process exited, code=exited, status=1/FAILURE
Nov 01 11:16:12 master-g4pnu-1893516417-g634g systemd[1]: Failed to start Set ownership to etcd3 data dir.
Nov 01 11:16:12 master-g4pnu-1893516417-g634g systemd[1]: set-ownership-etcd-data-dir.service: Unit entered failed state.
Nov 01 11:16:12 master-g4pnu-1893516417-g634g systemd[1]: set-ownership-etcd-data-dir.service: Failed with result 'exit-code'.
```

Also we should not use 3x `ExecStart` but rather 2x `ExecStartPre` + 1x `ExecStart`

**Comment by calvix** [comment]
> service set-ownership-etcd-data-dir.service on guest cluster fails on kvm

As you can see I stated that it fails on KVM.

I have lots of other work I want to do so I don't wanna take it now. Its part of security and CIS so i thnik its pretty important.

fyi @jgsqware

**Comment by jgsqware** [comment]
I'll take it

**Comment by xh3b4sd** [comment]
@jgsqware since you wanted to take this, is there some progress you want to share?

**Comment by jgsqware** [comment]
I'll take it today

**Comment by calvix** [comment]
This is not fixed, looks like my assumption was wrong.
```
Container Linux by CoreOS stable (1409.8.0)
Update Strategy: No Reboots
Failed Units: 1
  set-ownership-etcd-data-dir.service
calvix@master-n7i60-2749996164-18tdn ~ $ 
```

```
Dec 01 11:34:49 master-n7i60-2749996164-18tdn systemd[1]: Starting Set ownership to etcd3 data dir...
Dec 01 11:34:49 master-n7i60-2749996164-18tdn chmod[1146]: /usr/bin/chmod: /etc/kubernetes/data/etcd: No such file or directory
Dec 01 11:34:49 master-n7i60-2749996164-18tdn systemd[1]: set-ownership-etcd-data-dir.service: Main process exited, code=exited, status=1/FAILURE
Dec 01 11:34:49 master-n7i60-2749996164-18tdn systemd[1]: Failed to start Set ownership to etcd3 data dir.
Dec 01 11:34:49 master-n7i60-2749996164-18tdn systemd[1]: set-ownership-etcd-data-dir.service: Unit entered failed state.
Dec 01 11:34:49 master-n7i60-2749996164-18tdn systemd[1]: set-ownership-etcd-data-dir.service: Failed with result 'exit-code'.
```

I am not 100% right about all stuff so even if I say something please be sure to test everything and always before doing merge.

**Comment by jgsqware** [comment]
Agree with you @calvix. my bad, due to not the right branch in kvm-operator. This is fixed in the k8scloudconfig via https://github.com/giantswarm/k8scloudconfig/pull/250.

will be fixed when we go on master, or I can cherry-pick the change on the pinned branch

**Comment by calvix** [comment]
cool thanks :)
