### ISSUE TITLE
k8scc: update RBAC manifests to v1 api version

### ISSUE THREAD

**Issue by puja108** [giantswarm/k8scloudconfig#290]
we are currently still using the old api versions, which will get deprecated soon

**Comment by xh3b4sd** [comment]
How important is this actually? Is there a k8s version which removes the version we are currently using?

**Comment by puja108** [comment]
I think this is still not super urgent as 1.10 still supports the old format, but 1.11 might bring a deprecation galore. I'd label it boyscouting as it is very basic conversion

**Comment by xh3b4sd** [comment]
@giantswarm/sig-operator any taker?

**Comment by puja108** [comment]
IIRC just bump version. But better check. Our docs already have it

Puja
________________________________

**Comment by pipo02mix** [comment]
Is this only for k8s cloud config resources? or also cover all operators/services?

**Comment by pipo02mix** [comment]
done
