### ISSUE TITLE
k8scc: update deployments and daemonsets to apps/v1

### ISSUE THREAD

**Issue by puja108** [giantswarm/k8scloudconfig#291]
we are currently still using the old api versions, which will get deprecated soon

**Comment by rossf7** [comment]
Picking this up and will do daemonsets too.
https://kubernetes.io/docs/reference/workloads-18-19/#post-1-9

Will start with kube-state-metrics and node-exporter as they are being migrated to charts. We also need to make k8scc changes to remove these and will do the rest of the template updates at the same time.

**Comment by puja108** [comment]
@rossf7 so I guess you are doing it as part of migrating stuff to chart-operator for now right? the manifests inside k8scc we migrate later?

**Comment by puja108** [comment]
yeah, I think we just do it in chart-op for now, and then we'll see about the rest at some point

**Comment by rossf7** [comment]
I created giantswarm/giantswarm/issues/3194 for the managed services charts. This is done but we still need to do the remaining k8scloudconfig resources. Putting back on the backlog for now.

**Comment by xh3b4sd** [comment]
@puja108 would you like to lead a SIG project to get this done? Or what is missing here?

**Comment by puja108** [comment]
For me the biggest question/risk is not breaking updates, as I'm currently not sure if a apps/v1 DS might not just coexist with an old one. Cause we are not running any migration steps between k8scc versions, we would need to check if an upgrade doesn't result in duplicate DSs or deployments.

That said, I can just start and check into that, and I can even do some boyscouting on getting this done this week (in case the above blocker does not exist).

**Comment by xh3b4sd** [comment]
FMI got this addressed meanwhile?

**Comment by puja108** [comment]
No, I still see it in https://github.com/giantswarm/k8scloudconfig/blob/master/v_3_7_1/master_template.go

I think it would be good for @giantswarm/team-spirit to include it in the next k8s upgrade (1.13) and/or for @giantswarm/sig-infrastructure in the next calico upgrade (as other than the kube-proxy DS, calico should be the last deployment/DS in k8scc). On the note to latter, not sure why there's still IC and DNS deployments in latest k8scc when they're already managed by chart-operator.

maybe also good for @corest to keep in mind for the migration to ignition.

**Comment by tfussell** [comment]
This is done 😄
