### ISSUE TITLE
Use kubeadm

### ISSUE THREAD

**Issue by nhlfr** [giantswarm/k8scloudconfig#42]
Currently we are setting up Kubernetes components with systemd units. It would be nice to use kubeadm for that.

Pros:
- we can potentially get rid of the majority of the content of our cloudconfigs and don't define our own logic about deploying kubernetes
- apiserver, scheduler will become self-hosted
- it would take us closed to having fully self-hosted Kubernetes

Things to think about:
- [x] ~~Bootstraping master by kubeadm generated the token. We have two potential solutions:~~
  - ~~generate the token before and inject it somehow to kubeadm~~
  - ~~figure out the secure way of distributing the token to workers~~
This is solved, you can provide custom token to `kubeadm init`

Things to do:
- [x] Generate a token for kubeadm in cert-operator and put it into a secret
- [x] Fetch a token in aws/kvm-operator and put it as a parameter for cloudconfig generation in aws/kvm-operator, like we currently do with TLS assets
- [x] Change cloudconfig to use kubeadm
  - [x] Remove all services related to Kubernetes, etcd, Calico
  - [x] Create oneshot systemd unit for masters doing `kubeadm init --token ...`
  - [x] Create oneshot systemd unit for workers doing `kubeadm join --token --`
  - [x] Create oneshot systemd unit for masters waiting for workers availability (`kubectl get nodes` or API call), which will be a depencency of all the other units
  - [x] Create oneshot systemd unit for master for setting up self-hosted Calico
- [ ] Use the newest k8scloudconfig with kubeadm support in
  - [ ] kvm-operator
  - [ ] aws-operator

**Comment by puja108** [comment]
this would make a lot of things we do manually currently, a lot of the addon and cni stuff would be already in there and updated with new k8s releases, so we also wouldn't need to take care of a lot of upgrades that we currently need to do manually and one-by-one

**Comment by nhlfr** [comment]
I've updated the content a little bit and added some "working items".

**Comment by calvix** [comment]
Do we have spec for how we are going to handle certificates?

Also, where is the configuration file for `kubeadm`?  where we specify configuration param for api,  networks and so on.

**Comment by calvix** [comment]
Calico config seems to be wrong.
It's migrated to some file from the repository, why ? Is this properly tested?
https://github.com/giantswarm/k8scloudconfig/blob/master/templates.go#L319

file is 
https://github.com/projectcalico/calico/blob/master/v2.3/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml
there is some hard coded etcd endpoints without any certificates and so
https://github.com/projectcalico/calico/blob/master/v2.3/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml#L20

Also, i don't think this calico image will work:
https://github.com/projectcalico/calico/blob/master/v2.3/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml#L159

**Comment by xh3b4sd** [comment]
Lets close this issue for now. We will revive it as soon as it makes sense for us and we are working on the matter.
