### ISSUE TITLE
Use kubelet eviction policies

### ISSUE THREAD

**Issue by puja108** [giantswarm/k8scloudconfig#46]
We should start using eviction policies in guest clusters, this way we won’t run into cases where the guest clusters frags itself, we had the case at Vodafone and I also saw it completely destroying l8 cluster.

For a good overview see:
https://blog.kublr.com/learn-how-kubelet-eviction-policies-impact-cluster-rebalancing-2e976ebc53ea

Also in detail in docs:
https://kubernetes.io/docs/concepts/cluster-administration/out-of-resource/

**Comment by kopiczko** [comment]
@puja108 closing it's in later. Please reopen and put in inbox if relevant.

**Comment by puja108** [comment]
ack, reopening this

**Comment by xh3b4sd** [comment]
Are we doing this already? I have in mind something happened regarding this.

**Comment by puja108** [comment]
AFAIK we're not setting any of these flags, we should check the best practices and other things mentioned in the URLs above. We can still go down when the user overloads a node.

**Comment by puja108** [comment]
I guess we cover it in https://github.com/giantswarm/giantswarm/issues/2634

/cc @corest
