### ISSUE TITLE
calico-node unit fails to start due to invalid IP

### ISSUE THREAD

**Issue by rossf7** [giantswarm/k8scloudconfig#69]
Towards giantswarm/giantswarm#1388

Unit fails to start due to the error below. It looks like its because the env var BRIDGE_IP is not set. This is need to add a bgp peer using calicoctl.

```
Apr 30 15:50:11 master-1 bash[2332]: Invalid IP address specified.
Apr 30 15:50:11 master-1 systemd[1]: calico-node.service: Control process exited, code=exited status=1
```

See https://github.com/giantswarm/k8scloudconfig/blob/master/templates.go#L609

**Comment by calvix** [comment]
`BRIDGE_IP` is on our barematel setup IP of flannel bridge.
In AWS setup I think it should have value of ip address which is used for communication between workers and master. So one of the internal ip.

**Comment by rossf7** [comment]
Using the DEFAULT_IPV4 env var instead of BRIDGE_IP works for adding the bgp peer. Although the cloudconfig needs to work for aws and bare metal.

There is also a permissions issue. The unit needs to save the key /calico/v1/host/{{.Node.Hostname}}-flannel/bird_ip to etcd but this fails with an invalid cert error. However calling etcdctl manually with the cert args works so the cert is valid. We set the owner of the certs files to etcd so that might be the problem.

Lets discuss tomorrow when everyone is back.

**Comment by rossf7** [comment]
BRIDGE_IP issue was fixed by creating a oneshot unit that creates /etc/calico-environment and sets the bridge IP to the internal IP.
