### ISSUE TITLE
apiserver unit fails to start due to missing service account key

### ISSUE THREAD

**Issue by rossf7** [giantswarm/k8scloudconfig#70]
Towards giantswarm/giantswarm#1388

Unit fails to start because there is no key file at /etc/kubernetes/secrets/token_sign_key.pem

```
Apr 30 15:31:53 master-1 docker[3449]: I0430 15:31:53.171367       1 config.go:498] Will report 10.0.135.53 as public IP address.
Apr 30 15:31:53 master-1 docker[3449]: F0430 15:31:53.171721       1 server.go:244] Invalid Authentication Config: read /etc/kubernetes/secrets/token_sign_key.pem: is a directory
Apr 30 15:31:53 master-1 systemd[1]: k8s-api-server.service: Main process exited, code=exited, status=255/n/a
```

See https://github.com/giantswarm/k8scloudconfig/blob/master/templates.go#L705

**Comment by calvix** [comment]
This file is used for signing and verifying service account HTTP auth Tokens, in early days we just used  same file as private key for api (`apiserver-key.pem` in old naming).

The reason why we had a separate file for it is that when this file has to be same and persistent any every restart vault will generate new unique private key for api-server.
When the api start for first time its used to generate  `default-secret` and this secret will stay there. If you start api next time with different private-key auth tokens wont work until you manually delete default secret in all namespaces.

One of the solution was generate private key with `openssl` command  and put it on the persisten storage and then mount it into vm and this always use same file and wont break the service account token auth.

Another solution we had for g8s was storing the private key in vault as generic secret and then use vault docker image to fetch it. (it needed token ofc).  This was necessary when g8s was running multiple HA- masters and we needed this file to be same on all machines.

Its important to configure this option also into `controller-manager` service, so both are using same file.

Maybe the easiest solution for this now is to put it on persistent storage, if we can separate it from etcd data.

**Comment by rossf7** [comment]
Setting the token using the API key `--service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem` in both the apiserver and controller-manager means that both units will start. However as you say the private key needs to be saved to persistent storage.

Lets discuss tomorrow when everyone is back.

**Comment by calvix** [comment]
this is how we did it on old fleet infra

```
/bin/bash -c "/usr/bin/test ! -f /media/state/volumes/dev-k8s-master-vm-storage.service/secrets/token_sign_key.pem && umask 0377 && /usr/bin/openssl genrsa -out /media/state/volumes/dev-k8s-master-vm-storage.service/secrets/token_sign_key.pem 2048 && \
/usr/bin/echo 'Generated new token sign key.' || /usr/bin/echo 'Token sign key already exists, skipping.'"
```

**Comment by rossf7** [comment]
For storing the key I think we could use S3 and encrypt with KMS as we do for certs. For generating the key since it needs to persist across vault restarts we could do it in the operator.

https://golang.org/pkg/crypto/rsa/#GenerateKey

**Comment by xh3b4sd** [comment]
I take over to help out. My plan would be this. 

- To get going and unblock testing the first simple thing we can do is just adding another TPO in kubernetesd and cert-operator to create another key-pair. 
- Adding role configuration to the certificate TPR. That way certificates can be configured with very different TTLs. This does also prepare work for Kubernetes upgrades and works towards several customer requests around security and auditing. 
- Moving the PKI backend setup from cluster-service to cert-operator.
