### ISSUE TITLE
calico-node unit fails to start on worker nodes

### ISSUE THREAD

**Issue by rossf7** [giantswarm/k8scloudconfig#81]
The calico-node unit fails to start because its waiting for the calico client cert. Need to find out why certs aren't being decrypted on worker nodes.

**Comment by puja108** [comment]
I think this should be fixed now

**Comment by xh3b4sd** [comment]
@rossf7 I moved this to PDV since I think it is done.

**Comment by rossf7** [comment]
Yes its done. I should have moved it.
